using UnityEngine;

namespace arplace.ObjectManipulation
{
    /// <summary>
    /// Provides functionality to change the color of an object to a random color upon detecting a long press.
    /// Implements the ILongPressAction interface to respond to long press actions.
    /// </summary>
    public class ObjectColorChanger : MonoBehaviour, ILongPressAction
    {
        /// <summary>
        /// Called when a long press is detected. Changes the object's color to a random color.
        /// </summary>
        public void OnlongPress()
        {
            // Obtain the Renderer component from the child object to access its material.
            Renderer objectRenderer = GetComponentInChildren<Renderer>();

            // Set the material's color to a new random color generated by Random.ColorHSV().
            objectRenderer.material.color = Random.ColorHSV();
        }
    }
}
